### ISSUE TITLE
Load updates from GitHub

### ISSUE THREAD

**Issue by cagrimmett** [ronilaukkarinen/simple-dark-mode-for-wp-dashboard#2]
If you are planning on leaving this on GitHub only and not submitting it to the WP.org directory, you could add [a filter to load the plugin updates from GitHub](https://developer.wordpress.org/reference/hooks/update_plugins_hostname/) instead of WP.org with the [new Update URI](https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/) header.

**Comment by rollecode** [comment]
Yeah, that's what I do for other plugins but this is kinda still work in progress. Will consider releasing it on WP.org in some point. PRs welcome in the meantime!
