### ISSUE TITLE
Switch button to admin bar

### ISSUE THREAD

**Issue by 1ucay** [ronilaukkarinen/simple-dark-mode-for-wp-dashboard#3]
<?php
    /**
     * Plugin Name: Simple Dark Mode for WP Dashboard
     * Plugin URI: https://wordpress.org/plugins/simple-dark-mode-for-wp-dashboard/
     * Description: The simplest way to make your WordPress Dashboard dark
     * Author: Roni Laukkarinen
     * Author URI: https://github.com/ronilaukkarinen
     * Text Domain: dark-mode-dashboard
     * Version: 1.0.1
     *
     * @package dark-mode-dashboard
     */

    if ( ! defined( 'ABSPATH' ) ) {
    die();
    }

    define( 'SIMPLE_DARK_MODE_DASHBOARD_VERSION', '1.0.1' );
    define( 'SIMPLE_DARK_MODE_DASHBOARD_PLUGIN_PATH', plugin_dir_url( __FILE__ ) );

    add_filter( 'admin_body_class', 'core_dark_mode_admin_body_class' );
    function core_dark_mode_admin_body_class( $classes ) {

        if ( isset( $_COOKIE['dark-mode'] ) )
            $classes .= ' dark-mode';

        return $classes;
    }

    add_action( 'admin_init', 'core_dark_mode_admin_init' );
    function core_dark_mode_admin_init() {

        if ( isset( $_COOKIE['dark-mode'] ) ) {
            $user_id = get_current_user_id();
            do_action( 'doing_dark_mode', $user_id );
        }
    }

    add_filter( 'style_loader_tag',  'core_dark_mode_style_loader_tag', 10, 2 );
    function core_dark_mode_style_loader_tag( $html, $handle ){
        if ( strcmp( $handle, 'core-dark-mode') == 0 ) {
            if ( !isset( $_COOKIE['dark-mode'] ) )
                $html = str_replace("rel='stylesheet'", "rel='stylesheet' disabled", $html );
        }
        return $html;
    }

    add_filter( 'tiny_mce_before_init', 'core_dark_mode_tiny_mce_before_init' );
    function core_dark_mode_tiny_mce_before_init( $initArray ) {
        if ( isset( $_COOKIE['dark-mode'] ) ) {
            //$initArray['content_style'] = 'body { background: red }';
            $initArray['content_css'] = plugin_dir_url( __FILE__ ) . 'assets/css/dark-mode/css/prod/tinymce.css';
        }
        return $initArray;
    }

    add_action( 'admin_footer', 'core_dark_mode_admin_footer' );
    function core_dark_mode_admin_footer() {

        wp_enqueue_style( 'core-dark-mode', plugin_dir_url( __FILE__ ) . 'assets/css/dark-mode/css/prod/dark-mode.css', array(), filemtime( plugin_dir_path( __FILE__ ) . 'assets/css/dark-mode/css/prod/dark-mode.css' ) );

        wp_register_script( 'core-dark-mode', '' );
        wp_enqueue_script( 'core-dark-mode' );
        wp_add_inline_script( 'core-dark-mode', '
            function switchDarkMode( btn ) {
                var stylesheet = document.querySelector( "#core-dark-mode-css");
                document.body.classList.toggle("dark-mode");
                document.cookie = ( stylesheet.disabled ) ? "dark-mode=1; expires=Fri, 31 Dec 9999 23:59:59 GMT; SameSite=None; Secure" : "dark-mode=0; expires=Fri, 31 Dec 1975 23:59:59 GMT; SameSite=None; Secure";
                btn.querySelector("i").innerText = ( stylesheet.disabled ) ? "' . __( 'Disable Dark Mode', 'core' ) . '" : "' . __( 'Switch to Dark Mode', 'core' ) . '";
                stylesheet.disabled = ( stylesheet.disabled ) ? 0 : 1;
            }
        ');

        wp_add_inline_style( 'core-dark-mode', '
            #wp-admin-bar-core-dark-mode > .ab-item {
                user-select: none;
            }
            body.dark-mode #wp-admin-bar-core-dark-mode > .ab-item {
                background-color: var(--menu-current-background) !important;
            }
        ');
    }

    add_action( 'admin_bar_menu', 'core_dark_mode_admin_bar_menu' );
    function core_dark_mode_admin_bar_menu( \WP_Admin_Bar $bar ) {
        if ( is_admin() ) {
            $bar->add_menu( array(
                'id'     => 'core-dark-mode',
                'parent' => 'top-secondary',
                'href'   => 'javascript:;',
                'title' => '<span class="ab-icon dashicons dashicons-lightbulb" style="top:2px"></span><i>' . ( isset( $_COOKIE['dark-mode'] ) ? __( 'Disable Dark Mode', 'core' ) : __( 'Switch to Dark Mode', 'core' ) ) . '</i>',
                'meta'   => array(
                    'target'   => '_self',
                    'onclick'  => 'switchDarkMode(this);return false;',
                ),
            ) );
        }

    };

    ?>

tinymce.css - file should be generated by php itself, because of copy values in root

    :root {
        --color-paragraph: #f2f2f2;
        --color-background-default: #373737;
        --color-dark-grey: #191d24;
    }

    html {
        color-scheme: dark;
    }

    body {
        background-color: var(--color-background-default);
        color: var(--color-paragraph);
    }

    table tr td,
    table tr th {
        background-color: var(--color-dark-grey);
    }

**Comment by rollecode** [comment]
If you have code suggestions, can you please send pull requests?
