### ISSUE TITLE
new plugin - SEO framework / Members

### ISSUE THREAD

**Issue by 1ucay** [ronilaukkarinen/simple-dark-mode-for-wp-dashboard#4]
SEO framework ( Autodescription ) - metabox
https://cs.wordpress.org/plugins/autodescription/

    .tsf-flex-nav-tab-wrapper,
    .tsf-flex-setting-label,
    .tsf-flex-setting-input,
    .tsf-is-block-editor .tsf-flex-nav-tab-wrapper {
        background-color: var(--color-dark-grey)
    }
Members

    .members-cap-tabs .members-tab-nav,
    .members-tabs .members-tab-nav,
    .members-cp-role-list-wrap,
    .members-cap-tabs .members-tab-nav li[aria-selected="true"] a,
    .members-tabs .members-tab-nav li[aria-selected="true"] a {
        background-color: var(--color-dark-grey)
    }
    .members-cap-tabs,
    .members-tabs {
        background: var(--color-dark-grey)
    }

**Comment by rollecode** [comment]
Can you send a PR?
