### ISSUE TITLE
Invisible Post date on publishing

### ISSUE THREAD

**Issue by Asecchi83** [ronilaukkarinen/simple-dark-mode-for-wp-dashboard#5]
Hi Roni,

first of all thanks for this plugin, I was looking for something like it for the dashboard only and this is the best one I found.

I just wanted to report a little issue I found. In the following screen you can see I have black data fields. If I select and write in it works, but I can't see the numbers. Before writing here I tried a lot with the CSS but I could not find the right way to manage it.

![immagine_2024-05-16_092200728](https://github.com/ronilaukkarinen/simple-dark-mode-for-wp-dashboard/assets/169978867/9e56136f-9539-4ab1-88d2-69449b7c201b)

I think you would be definitely faster than me in finding the right place to edit.

Thanks!

Alex

**Comment by rollecode** [comment]
I know, it’s incomplete in MANY parts. I’m way too busy so instead of fixing them I have just been living with them 😅

So the same applies than in issue #1: 

> Thanks for the issue. I realize there might be some UI glitches on some parts especially in the Gutenberg after WordPress updates and I have not been able to keep it up. I currently run this plugin on my personal site where I write daily, I just wanted to have a dark writing ground as I use WP admin directly on my mobile phone.
> 
> I'll try to fix these in some point but as I'm very busy it won't happen soon. So pull requests are always welcome.

If you know CSS, please send PRs! Thanks!

**Comment by Asecchi83** [comment]
OK! If I find the solution I keep you updated!
