### ISSUE TITLE
Better and simple solution CSS

### ISSUE THREAD

**Issue by 1ucay** [ronilaukkarinen/simple-dark-mode-for-wp-dashboard#8]
What about CSS over simple this =>

https://dev.to/madsstoumann/dark-mode-in-3-lines-of-css-and-other-adventures-1ljj
`

    /*
    :where(html) :not(img) {
        background-color: Canvas !important;
        color: CanvasText !important;
        color-scheme: light dark;
        border-color: CanvasText !important;
    }
    */
    
    :where(html) :not(img),
    *:before {
        background-color: color-mix(in srgb, Canvas, CanvasText 90%) !important;
        color: color-mix(in srgb, CanvasText, Canvas 55%) !important;
        border-color: color-mix(in srgb, CanvasText, Canvas 55%) !important;
        fill: color-mix(in srgb, CanvasText, Canvas 55%) !important;
    }

`

**Comment by rollecode** [comment]
That makes it way too bland and inaccessible unfortunately.

![image](https://github.com/user-attachments/assets/b340c165-6e96-4119-83c6-242267cc7d2f)

There is no silver bullet.

**Comment by 1ucay** [comment]
Try new code :)
Based on https://monochrome.sutic.nu/2024/02/25/hue-preserving-invert-css-filter-for-dark-mode.html

Append to begin on body element.



    <svg style="position:fixed; left:0; top:0; width:0; height:0">
        <defs>
            <filter id="invert-luminance"
                color-interpolation-filters="linearRGB">
                <feComponentTransfer>
                    <feFuncR type="gamma"
                        amplitude="1"
                        exponent="0.5"
                        offset="0.0" />
                    <feFuncG type="gamma"
                        amplitude="1"
                        exponent="0.5"
                        offset="0.0" />
                    <feFuncB type="gamma"
                        amplitude="1"
                        exponent="0.5"
                        offset="0.0" />
                    <feFuncA type="gamma"
                        amplitude="1"
                        exponent="1"
                        offset="0.0" />
                </feComponentTransfer>
                <feColorMatrix type="matrix" values="
                    1.103 -1.761 -0.342 0.000 1.000 
                    -0.897 0.239 -0.342 0.000 1.000 
                    -0.897 -1.761 1.658 0.000 1.000 
                    0.000 0.000 0.000 1.000 0.000 
            " />
            </filter>
        </defs>
    </svg>

    <style>
        
        @import url(css/colors/light/colors.min.css);

        html {
            filter: url(#invert-luminance) hue-rotate(180deg);
        }
        
        html img,
        html video {
            filter: invert(105%) hue-rotate(360deg) brightness(1.2) contrast(1.1) saturate(.48);
        } 
        
        html:has(:fullscreen),
        html:has(:fullscreen) video {
            filter: none;
        }

    </style>
